# Generated by Django 5.1.7 on 2025-03-27 13:32

import django.db.models.deletion
import django.utils.timezone
import habit_tracker.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['user', 'time'], 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AddField(
            model_name='habit',
            name='action',
            field=models.CharField(default='Новое действие', max_length=255, verbose_name='Действие'),
        ),
        migrations.AddField(
            model_name='habit',
            name='associated_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_habits', to='habit_tracker.habit', verbose_name='Связанная привычка'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_pleasant',
            field=models.BooleanField(default=False, verbose_name='Приятная привычка'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичная привычка'),
        ),
        migrations.AddField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveIntegerField(default=1, validators=[habit_tracker.validators.PeriodicityValidator], verbose_name='Периодичность (в днях)'),
        ),
        migrations.AddField(
            model_name='habit',
            name='place',
            field=models.CharField(default='Не указано', max_length=255, verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вознаграждение'),
        ),
        migrations.AddField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='habit',
            name='time_to_complete',
            field=models.PositiveIntegerField(default=60, validators=[habit_tracker.validators.TimeToCompleteValidator], verbose_name='Время на выполнение (в секундах)'),
        ),
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
    ]
